// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwjFxQjv6EB9_uNHe1EQDlIYrbwUlj24',
    appId: '1:963592796939:web:027b2014de1a98ecfac00e',
    messagingSenderId: '963592796939',
    projectId: 'flutter-map-6e241',
    authDomain: 'flutter-map-6e241.firebaseapp.com',
    storageBucket: 'flutter-map-6e241.appspot.com',
    measurementId: 'G-8QR0GDK4RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mfDeoB0QR872cwhx9KYRjGlMx_JlgMI',
    appId: '1:963592796939:android:cc24e16b87a6c0f8fac00e',
    messagingSenderId: '963592796939',
    projectId: 'flutter-map-6e241',
    storageBucket: 'flutter-map-6e241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxB7cKPF2NlahdybRholgWyPXlg_g9Fgs',
    appId: '1:963592796939:ios:971a7d64687b9053fac00e',
    messagingSenderId: '963592796939',
    projectId: 'flutter-map-6e241',
    storageBucket: 'flutter-map-6e241.appspot.com',
    iosBundleId: 'me.jpryan.flutterMapExample',
  );

}